apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  labels: 
    app: registry
spec:
  storageClassName: registry-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: registry
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7.1
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5 
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 5000
          name: default
        volumeMounts:
        - name: registry-persistent-storage
          mountPath: /var/lib/registry
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
      volumes:
      - name: registry-persistent-storage
        persistentVolumeClaim:
          claimName: registry-pv-claim
      - name: config
        configMap:
          name: registry
          items:
          - key: registry-config.yml
            path: config.yml