apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: registry-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry-volume
  namespace: registry
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: registry-storage
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/registry"